# Generated by Django 4.2.1 on 2023-08-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('senha', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO'), ('Prefiro não informar', 'PREFIRO NÃO INFORMAR')], max_length=20)),
                ('cod_matricula', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('carga_horaria', models.TimeField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_coordenador', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('senha', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO'), ('Prefiro não informar', 'PREFIRO NÃO INFORMAR')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.FloatField()),
                ('status', models.CharField(choices=[('Aprovado', 'APROVADO'), ('Em Análise', 'EM ANÁLISE'), ('Recusado', 'RECUSADO')], max_length=10)),
                ('comprovante', models.FileField(upload_to='')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.aluno')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.categoriaac')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.coordenador')),
            ],
        ),
    ]
