# Generated by Django 4.2.1 on 2023-08-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_ac_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
