# Generated by Django 4.2.1 on 2023-08-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_coordenador_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaac',
            old_name='carga_horaria',
            new_name='carga_horaria_maxima',
        ),
    ]
