# Generated by Django 4.2.4 on 2023-08-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_carga_horaria_categoriaac_carga_horaria_maxima'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ac',
            old_name='comprovante',
            new_name='certificado',
        ),
        migrations.AddField(
            model_name='ac',
            name='descricao',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ac',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.aluno'),
        ),
        migrations.AlterField(
            model_name='ac',
            name='carga_horaria',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ac',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.categoriaac'),
        ),
        migrations.AlterField(
            model_name='ac',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.coordenador'),
        ),
        migrations.AlterField(
            model_name='ac',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'APROVADO'), ('Em Análise', 'EM ANÁLISE'), ('Recusado', 'RECUSADO')], default='ANÁLISE', max_length=10),
        ),
        migrations.AlterField(
            model_name='categoriaac',
            name='carga_horaria_maxima',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='categoriaac',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
    ]
