# Generated by Django 4.2.4 on 2023-08-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_comprovante_ac_certificado_ac_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='ac',
            name='certificado',
            field=models.FileField(upload_to='static/certifications/'),
        ),
        migrations.AlterField(
            model_name='ac',
            name='descricao',
            field=models.CharField(default='', max_length=200, verbose_name='Descrição'),
        ),
    ]
