# Generated by Django 4.2.4 on 2023-08-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_ac_carga_horaria_alter_ac_certificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac',
            name='coordenador',
        ),
        migrations.DeleteModel(
            name='Coordenador',
        ),
    ]
